# Generated by Django 4.2.5 on 2023-09-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='roll_np',
            new_name='roll_no',
        ),
    ]
