# Generated by Django 4.2.5 on 2023-09-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_itemdeatil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDeatil',
            new_name='ItemDetail',
        ),
    ]
